# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item_response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("item_response.proto", :syntax => :proto3) do
    add_message "ItemResponse" do
      optional :id, :int64, 1
      optional :title, :string, 2
    end
  end
end

ItemResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ItemResponse").msgclass
